[tool.poetry]
name = "nonebot-plugin-lolinfo"
version = "0.1.0"
description = "以图片形式将 英雄联盟(LOL) 的各种数据进行互通"
authors = ["Shadow403"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
httpx = "^0.27.0"
nonebot2 = "^2.3.3"

[tool.poetry.group.dev.dependencies]
httpx = "^0.27.0"
nonebot2 = "^2.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
